---
total_semantic_labels: 129
dynamic_labels: []
invalid_labels: []
object_labels:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  - 19
  - 20
  - 21
  - 22
  - 23
  - 24
  - 25
  - 26
  - 27
  - 28
  - 29
  - 30
  - 31
  - 32
  - 33
  - 34
  - 35
  - 36
  - 37
  - 38
  - 39
  - 40
  - 41
  - 42
  - 43
  - 44
  - 45
  - 46
  - 47
  - 48
  - 49
  - 50
  - 51
  - 52
  - 53
  - 54
  - 55
  - 56
  - 57
  - 58
  - 59
  - 60
  - 61
  - 62
  - 63
  - 64
  - 65
  - 66
  - 67
  - 68
  - 69
  - 70
  - 71
  - 72
  - 73
  - 74
  - 75
  - 76
  - 77
  - 78
  - 79
  - 80
  - 81
  - 82
  - 83
  - 84
  - 85
  - 86
  - 87
  - 88
  - 89
  - 90
  - 91
  - 92
  - 93
  - 94
  - 95
  - 96
  - 97
  - 98
  - 99
  - 100
  - 101
  - 102
  - 103
  - 104
  - 105
  - 106
  - 107
  - 108
  - 109
  - 110
  - 111
  - 112
  - 113
  - 114
  - 115
  - 116
  - 117
  - 118
  - 119
  - 120
  - 121
  - 122
  - 123
  - 124
  - 125
  - 126
  - 127
  - 128
surface_places_labels: []
label_names:
  - {label: 0, name: action_figure}
  - {label: 1, name: android_figure}
  - {label: 2, name: apple}
  - {label: 3, name: backpack}
  - {label: 4, name: baseballbat}
  - {label: 5, name: basket}
  - {label: 6, name: basketball}
  - {label: 7, name: bath_towel}
  - {label: 8, name: battery_charger}
  - {label: 9, name: board_game}
  - {label: 10, name: book}
  - {label: 11, name: bottle}
  - {label: 12, name: bowl}
  - {label: 13, name: box}
  - {label: 14, name: bread}
  - {label: 15, name: bundt_pan}
  - {label: 16, name: butter_dish}
  - {label: 17, name: c-clamp}
  - {label: 18, name: cake_pan}
  - {label: 19, name: can}
  - {label: 20, name: can_opener}
  - {label: 21, name: candle}
  - {label: 22, name: candle_holder}
  - {label: 23, name: candy_bar}
  - {label: 24, name: canister}
  - {label: 25, name: carrying_case}
  - {label: 26, name: casserole}
  - {label: 27, name: cellphone}
  - {label: 28, name: clock}
  - {label: 29, name: credit_card}
  - {label: 30, name: cup}
  - {label: 31, name: cushion}
  - {label: 32, name: doll}
  - {label: 33, name: dumbbell}
  - {label: 34, name: egg}
  - {label: 35, name: electric_kettle}
  - {label: 36, name: electronic_cable}
  - {label: 37, name: file_sorter}
  - {label: 38, name: folder}
  - {label: 39, name: fork}
  - {label: 40, name: gaming_console}
  - {label: 41, name: glass}
  - {label: 42, name: hammer}
  - {label: 43, name: hand_towel}
  - {label: 44, name: handbag}
  - {label: 45, name: hard_drive}
  - {label: 46, name: hat}
  - {label: 47, name: helmet}
  - {label: 48, name: jug}
  - {label: 49, name: kettle}
  - {label: 50, name: keychain}
  - {label: 51, name: knife}
  - {label: 52, name: ladle}
  - {label: 53, name: lamp}
  - {label: 54, name: laptop}
  - {label: 55, name: laptop_cover}
  - {label: 56, name: laptop_stand}
  - {label: 57, name: lunch_box}
  - {label: 58, name: milk_frother_cup}
  - {label: 59, name: monitor_stand}
  - {label: 60, name: mouse_pad}
  - {label: 61, name: multiport_hub}
  - {label: 62, name: pan}
  - {label: 63, name: pen}
  - {label: 64, name: pencil_case}
  - {label: 65, name: phone_stand}
  - {label: 66, name: picture_frame}
  - {label: 67, name: pitcher}
  - {label: 68, name: plant_container}
  - {label: 69, name: plant_saucer}
  - {label: 70, name: plate}
  - {label: 71, name: potato}
  - {label: 72, name: ramekin}
  - {label: 73, name: scissors}
  - {label: 74, name: screwdriver}
  - {label: 75, name: shoe}
  - {label: 76, name: soap_dish}
  - {label: 77, name: soap_dispenser}
  - {label: 78, name: spatula}
  - {label: 79, name: spectacles}
  - {label: 80, name: spicemill}
  - {label: 81, name: sponge}
  - {label: 82, name: spoon}
  - {label: 83, name: spray_bottle}
  - {label: 84, name: squeezer}
  - {label: 85, name: statue}
  - {label: 86, name: stuffed toy}
  - {label: 87, name: stuffed_toy}
  - {label: 88, name: sushi_mat}
  - {label: 89, name: tape}
  - {label: 90, name: teapot}
  - {label: 91, name: tennis_racquet}
  - {label: 92, name: tissue_box}
  - {label: 93, name: tomato}
  - {label: 94, name: toy_airplane}
  - {label: 95, name: toy_animal}
  - {label: 96, name: toy_bee}
  - {label: 97, name: toy_cactus}
  - {label: 98, name: toy_construction_set}
  - {label: 99, name: toy_fire_truck}
  - {label: 100, name: toy_food}
  - {label: 101, name: toy_fruits}
  - {label: 102, name: toy_pineapple}
  - {label: 103, name: toy_swing}
  - {label: 104, name: toy_vehicle}
  - {label: 105, name: tray}
  - {label: 106, name: vase}
  - {label: 107, name: watch}
  - {label: 108, name: bathtub}
  - {label: 109, name: bed}
  - {label: 110, name: bench}
  - {label: 111, name: cabinet}
  - {label: 112, name: chair}
  - {label: 113, name: chest_of_drawers}
  - {label: 114, name: couch}
  - {label: 115, name: counter}
  - {label: 116, name: filing_cabinet}
  - {label: 117, name: hamper}
  - {label: 118, name: serving_cart}
  - {label: 119, name: shelves}
  - {label: 120, name: shoe_rack}
  - {label: 121, name: sink}
  - {label: 122, name: stand}
  - {label: 123, name: stool}
  - {label: 124, name: table}
  - {label: 125, name: toilet}
  - {label: 126, name: trunk}
  - {label: 127, name: wardrobe}
  - {label: 128, name: washer_dryer}
